development:
  dialect: "mysql"
  database: "gotrue_development"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "Freedumn2!"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@(localhost:3306)/gotrue_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/gotrue_production?parseTime=true&multiStatements=true&readTimeout=1s"}}